### ISSUE TITLE
Abnormal program termination: received signal 11 (Segmentation fault)

### ISSUE THREAD

**Issue by AadityaKhetan** [Yixin-Hu/TetWild#79]
Abnormal program termination: received signal 11 (Segmentation fault) while running tetwild in ubuntu. I am using command -
sudo docker run --rm -v "$(pwd)":/shared yixinhu/tetwild --input test1.stl --output test.msh

**Comment by Yixin-Hu** [comment]
Hi, could you share the log?

**Comment by Arthur-272** [comment]
Hi there, we are working together and here is the log that you asked for.
![image](https://user-images.githubusercontent.com/46446130/111422778-3baa1f80-8715-11eb-9f80-57a11066ba09.png)

**Comment by Arthur-272** [comment]
Hey there, thank you for the reply, the issue has been solved. 
We just needed to go to the directory where the object file was stored and run it there and then VOILA!. Not sure what is the explanation behind this, but whatever keeps the ball rolling!

**Comment by Yixin-Hu** [comment]
That makes sense. The termination looks like related to the input or the input parser.

**Comment by aprath1** [comment]
> Hey there, thank you for the reply, the issue has been solved. We just needed to go to the directory where the object file was stored and run it there and then VOILA!. Not sure what is the explanation behind this, but whatever keeps the ball rolling!

@Arthur-272 I am still having this issue, did you run it in Ubuntu?
Do you mean to run from the directory where the .STL file is located, if so could you please let me know how you mounted the directory, with '-v' command

**Comment by aprath1** [comment]
For any one else scratching their heads on this here is what worked for me (it's simple stuff, but you got to get that ri8 else it wont just run you know!!).
1. Put your test.stl object in a folder (named 'data' here) and this **need to be** inside your current working directory (=>  "$(pwd)")
2. modify the command like this
`sudo docker run --rm -v "$(pwd)":/data yixinhu/tetwild --input data/Spinner_Press.stl --output data/test.msh`

**Comment by xk-huang** [comment]
> 

xI changed `data/Spinner_Press.stl` to `/data/Spinner_Press.stl`, and it worked.
